# Generated by Django 3.2.9 on 2021-12-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_property_additionalcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='pageDescription',
            field=models.TextField(default='', null=True),
        ),
    ]
