# Generated by Django 3.2.9 on 2021-12-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalId', models.TextField()),
                ('areaSqm', models.IntegerField()),
                ('city', models.TextField()),
                ('furnish', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('postalCode', models.TextField()),
                ('propertyType', models.TextField()),
                ('rent', models.IntegerField()),
                ('title', models.TextField()),
            ],
        ),
    ]
