# Generated by Django 3.2.9 on 2021-12-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='additionalCost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='coverImageUrl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='deposit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='descriptionTranslated',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='gender',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='isRoomActive',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pageDescription',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='property',
            name='pageTitle',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='property',
            name='pets',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='property',
            name='roommates',
            field=models.CharField(default='', max_length=10),
        ),
    ]
