# Generated by Django 3.2.9 on 2021-12-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_property_pagedescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
