# Generated by Django 3.2.9 on 2021-12-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_property_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='pageTitle',
            field=models.TextField(default='', null=True),
        ),
    ]
