# Generated by Django 3.2.9 on 2021-12-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_property_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='roommates',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
